# Generated by Django 3.1.5 on 2021-02-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAffairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('NationalNews', models.TextField(blank=True, max_length=2000)),
                ('InternationalNews', models.TextField(blank=True, max_length=2000)),
                ('BooksAndAuthor', models.TextField(blank=True, max_length=500)),
                ('AppointmentAndResignation', models.TextField(blank=True, max_length=500)),
                ('AwardsAndHonours', models.TextField(blank=True, max_length=500)),
                ('ImportantDays', models.TextField(blank=True, max_length=500)),
                ('Obituary', models.TextField(blank=True, max_length=500)),
                ('Sports', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
