# Generated by Django 3.1.5 on 2021-02-26 12:06

import achievers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('partsofspeech', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('meaning', models.TextField(max_length=500)),
                ('sentence', models.TextField(max_length=500)),
                ('synonyms', models.CharField(max_length=100)),
                ('antonyms', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=achievers.models.save_subject_image, verbose_name='Subject Image')),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
