# Generated by Django 3.1.5 on 2021-02-26 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('achievers', '0002_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='vocabulary_id',
            field=models.CharField(default=datetime.datetime(2021, 2, 26, 12, 28, 46, 87882, tzinfo=utc), max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
