# Generated by Django 3.1.5 on 2021-02-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievers', '0005_auto_20210227_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examAnalysis_id', models.CharField(max_length=100, unique=True)),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('examPattern', models.TextField(max_length=500)),
                ('goodAttempt', models.TextField(max_length=1000)),
                ('english', models.TextField(max_length=3000)),
                ('maths', models.TextField(max_length=3000)),
                ('reasoning', models.TextField(max_length=3000)),
                ('generalAwareness', models.TextField(max_length=3000)),
                ('generalStudies', models.TextField(max_length=3000)),
                ('footer', models.CharField(max_length=100)),
            ],
        ),
    ]
